# Generated by Django 5.2.5 on 2025-08-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=256)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'etiqueta',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modificado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.TextField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('etiquetas', models.ManyToManyField(blank=True, db_table='tarefa_etiqueta', related_name='tarefas', to='tasks.etiqueta')),
                ('grupo', models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='tasks.grupo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
